FPS = 40
SCREEN_MULTIPLIER = 2
WIDTH = 400 * SCREEN_MULTIPLIER
HEIGHT = 300 * SCREEN_MULTIPLIER
SCREEN_SIZE = (WIDTH, HEIGHT)
SKY_HEIGHT = 100 * SCREEN_MULTIPLIER

BOMB_STEP_INCREMENT = 1 * SCREEN_MULTIPLIER
MAX_BOMB_STEP = 10 * SCREEN_MULTIPLIER

BOMBER_STEP_INCREMENT = 2 * SCREEN_MULTIPLIER
MAX_BOMBER_STEP = 14 * SCREEN_MULTIPLIER

LEVEL_LENGTH_INCREMENT = 2000
MAX_LEVEL_LENGTH = 20000

DROP_INTERVAL_DECREMENT = 40
MIN_DROP_INTERVAL = 70



KABOOM = 40
CAUGHT = 41
#hello there!
#general kenobi!
